### ISSUE TITLE
petsc and slepc version is not up to date in homebrew

### ISSUE THREAD

**Issue by aslakbergersen** [optimizers/homebrew-fenics#15]
First of all thank you for making this. I have just used this to install FEniCS on my 10.11 Mac, and had some small issues. When doing

`PETSC_DIR=/usr/local/opt/petsc/real SLEPC_DIR=/usr/local/opt/slepc/real pip install mpi4py petsc4py slepc4py`

it complains that:

`Could not find a version that satisfies the requirement petsc<3.8,>=3.7 (from petsc4py) (from versions: )
No matching distribution found for petsc<3.8,>=3.7 (from petsc4py)`

Since homebrew installs both petsc and slepc with 3.6, while pip tries to install 3.7, you have to do

`PETSC_DIR=/usr/local/opt/petsc/real SLEPC_DIR=/usr/local/opt/slepc/real pip install mpi4py petsc4py==3.6.0 slepc4py==3.6.0`

For the versions to be compatible.

I do not know what is the best solution, to bump the version in Homebrew to be the newest version of petsc or to use an older version in the pip install?

**Comment by aslakbergersen** [comment]
In addition I needed to install sympy with pip, so it should perhaps be added such that you do:

`PETSC_DIR=/usr/local/opt/petsc/real SLEPC_DIR=/usr/local/opt/slepc/real pip install mpi4py petsc4py==3.6.0 slepc4py==3.6.0 sympy`

**Comment by dpo** [comment]
Thanks for the feedback. You're right that the versions in Homebrew should be bumped. I'll also update the build instructions following your comments but I wonder why you had to install `sympy` explicitly while I didn't need to on TravisCI.

**Comment by aslakbergersen** [comment]
The build when through without sympy, but when doing 

`import dolfin`

I got:

```
---------------------------------------------------
DOLFIN runtime dependency is not met.
Install the following python module: 'ffc' 
and make sure its location is listed in PYTHONPATH.
---------------------------------------------------
```

When I only imported ffc, it stopped when trying to import sympy. After I installed sympy it worked. Do you test the installation on TravisCI?

**Comment by dpo** [comment]
See https://github.com/Homebrew/homebrew-science/pull/3710.

**Comment by dpo** [comment]
The Homebrew versions of PETSc and SLEPc have been updated.
