### ISSUE TITLE
Renaming PETSc formula causes "No available formula for petsc" error

### ISSUE THREAD

**Issue by goxberry** [optimizers/homebrew-fenics#2]
Renaming the PETSc formula in https://github.com/optimizers/homebrew-fenics/commit/996b82cb6a16a6746be9e18aaa3214c77c0d6696 causes the error

```
bash-3.2$ brew install optimizers/fenics/petsc --env=std
Error: No available formula for petsc
```

Reverting the commit resolves the problem.

**Comment by dpo** [comment]
Please `brew update`.
