### ISSUE TITLE
Isolating PETSc downloaded libraries

### ISSUE THREAD

**Issue by goxberry** [optimizers/homebrew-fenics#3]
Something I noticed with the installation process is that the PETSc libraries will be symlinked into `$(brew --prefix)/lib` and the PETSc headers will be symlinked into `$(brew --prefix)/include`. Some of these headers and libraries will conflict with installed headers and libraries from other packages, like:

- metis
- parmetis
- suite-sparse
- scalapack
- mumps

In the short term, `brew link --overwrite petsc-fenics` is fine; in the longer term, is it possible to isolate the PETSc versions of libraries and headers from system versions of these packages? Some PETSc packages have patches that have not been migrated to upstream, so it's not clear to me that PETSc should use the system packages instead of downloading its own. It's also not clear if there will be later conflicts with other packages that depend on METIS, ParMETIS, etc., or if other software later installed outside of Homebrew will pick up the wrong headers and libraries as a result of the symlink conflicts. The version of PETSc from Homebrew core would probably experience similar conflicts if it downloaded external packages for PETSc. 

I'm willing to help write a patch and discuss ideas, if you think this behavior is an issue worth resolving.

**Comment by dpo** [comment]
I'm going to close this as almost everything has changed since this issue was opened. I just merged updates to version 1.6.0 of all packages. Please open a new issue if there are still difficulties.
