### ISSUE TITLE
setting PETSC_DIR

### ISSUE THREAD

**Issue by lukeolson** [optimizers/homebrew-fenics#5]
I've been updating to dolfin 1.5 in the dolfin1.5 branch and I'm having trouble getting the Formula to find PETSc.  Even if I explicitly set `ENV['PETSC_DIR']`:
https://github.com/optimizers/homebrew-fenics/blob/e757b00029f3554c44334bf06a1ecaa0a95a954e/dolfin.rb#L42

The build sets it to `/usr/local`:

```
- Checking for package 'PETSc'
-- PETSC_DIR is /usr/local
-- PETSC_ARCH is empty
-- Found petscconf.h
/tmp/dolfin20150402-42998-ujxvt9/dolfin-1.5.0/build/Makefile.petsc:4: /usr/local/conf/variables: No such file or directory
make: *** No rule to make target `/usr/local/conf/variables'.  Stop.
```

It looks like `petscconf.h` is found in `/usr/local/include` because of a link, but then from there it cannot find `conf/variables`.  Any ideas?  I have `PETSC_DIR` set as well and have tried `--env-std`

**Comment by lukeolson** [comment]
@dpo Any ideas on this?  Other formulae set 
```
ENV['PETSC_DIR'] = Formula['petsc'].opt_prefix
```
but that doesn't seem to work here.

**Comment by dpo** [comment]
Does it work if you set
````
ENV["PETSC_DIR"] = "#{Formula["petsc"].opt_prefix}/real"
```
or perhaps
````
ENV["PETSC_DIR"] = Formula["petsc"].opt_prefix
ENV["PETSC_ARCH"] = "real"
````
Recently, we modified `petsc.rb` to build both the real and complex libraries.

**Comment by dpo** [comment]
Oh sorry, you're building `petsc-fenics`. Let me have a look.

**Comment by dpo** [comment]
Check the `dolfin1.5-debug` branch. I cleaned up the formulas and `dolfin` detects PETSc and SLEPc. I'm a bit confused because several dependencies seems to have disappeared from `dolfin.rb`. Currently, the build breaks because MUMPS can't be found. Several other dependencies could be optional (e.g., `trilinos` and `pastix`).

**Comment by lukeolson** [comment]
Hmm.  I get something slightly different than before; still PETSc is not found:

```
-- Check size of PetscInt - done
-- PETSc could not be found. Be sure to set PETSC_DIR and PETSC_ARCH. (missing:  PETSC_TEST_RUNS) (Required is at least version "3.3")
-- Performing Test PARMETIS_TEST_RUNS
```

```
-- The following optional packages were not found:
-- -----------------------------------------------
-- (**) OPENMP
-- (**) PETSC
-- (**) PETSC4PY
-- (**) SLEPC
-- (**) SLEPC4PY
```

There's something odd about paths here.  Why is it that `env :std` is needed?

Also, if I took out any deps from `dolfin.rb` it was for debugging.

**Comment by lukeolson** [comment]
Even so the build completes and some basic demos work fine.  I'll debug a bit more.

**Comment by dpo** [comment]
That's odd. I get
````
-- Found PETSc: /usr/local/Cellar/petsc/3.5.3_2/real/lib/libpetsc.dylib (Required is at least version "3.3")
````
Did you try to wipe out your PETSc, and to reinstall a fresh one?

**Comment by dpo** [comment]
Are you using bottles or building from source?

**Comment by lukeolson** [comment]
Ok, if I brew petsc by source instead of bottle then `dolfin.rb` picks it up.  But if `dolfin.rb` installs it as a dep it will pour it by default.  Not sure what to do with that.

**Comment by dpo** [comment]
I'm not quite sure where the difference is, but you can ensure you always build from source by setting `HOMEBREW_BUILD_FROM_SOURCE=1` in your `~/.bashrc`.

**Comment by dpo** [comment]
Not sure what to do with this:
````
Undefined symbols for architecture x86_64:
  "_dmumps_c", referenced from:
      dolfin::MUMPSLUSolver::solve(dolfin::GenericVector&, dolfin::GenericVector const&) in MUMPSLUSolver.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
````
I don't see any way to configure MUMPS and setting `MUMPS_DIR` doesn't help.

**Comment by dpo** [comment]
@lukeolson please have a look at the [`dolfin160`](https://github.com/optimizers/homebrew-fenics/tree/dolfin160) branch. I'm still hitting the MUMPS error mentioned above, but everything else is quite smooth.

**Comment by lukeolson** [comment]
OK I tried this a few weeks ago and ran into the same MUMPS error.  Any ideas on getting past this?

I'll try the current branch again to see where it goes.

**Comment by dpo** [comment]
Don't know how to get past the MUMPS error yet. Working on it.

**Comment by lukeolson** [comment]
I checked the latest on https://github.com/optimizers/homebrew-fenics/tree/dolfin160 and made some small updates:

- `pip install ply` is required since there is not build in homebrew python
- explicit on `openmpi` since one cannot just `brew install mpi` (that I know of)

Quesion: why is `homebrew/python/numpy` preferred over pypi?

In the end, same result:

```
[ 93%] Linking CXX shared library libdolfin.dylib
Undefined symbols for architecture x86_64:
  "_dmumps_c", referenced from:
      dolfin::MUMPSLUSolver::solve(dolfin::GenericVector&, dolfin::GenericVector const&) in MUMPSLUSolver.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [dolfin/libdolfin.1.6.0.dylib] Error 1
make[1]: *** [dolfin/CMakeFiles/dolfin.dir/all] Error 2
make: *** [all] Error 2
```

I'll keep digging as well.

**Comment by dpo** [comment]
You don't want to depend on `open-mpi` explicitly. That's what `depends_on :mpi` is for. It's a requirement that will be satisfied if either `open-mpi` or `mpich` is installed. By default, `open-mpi` will be installed if neither is already present.

Yes, `pip install ply` is required. I'll update that.

**Comment by dpo** [comment]
You're right, there's no reason to prefer `homebrew/python/numpy`. It's enough to specify `depends_on "numpy" => :python`.

**Comment by lukeolson** [comment]
> You don't want to depend on open-mpi explicitly. That's what depends_on :mpi is for

Oh right.  I meant in the mpi install instructions...they used to say `brew install mpi` which will not work

**Comment by dpo** [comment]
Gotcha! Thanks for spotting that!

**Comment by lukeolson** [comment]
@dpo I think I know what's going on with the MUMPS error.  When `mumps` is installed as a brew formula, the relevant library is `libdmumps.dylib`.  However dolfin does not find this...it doesn't look.  However, if you modify the `petsc` build to `--download-mumps=1` (instead of `--with-mumps` and the brew path) dolfin finds the mumps library.  The work around is to either
1. patch the dolfin build with a `dyld_library_path` or similar
or
2. maintain an alternate `petsc` build (which is what we were doing before).

I would prefer not to have an alternate petsc build.

**Comment by dpo** [comment]
@lukeolson Thanks for determining that! I would also prefer to not have an alternate PETSc build. Do you know what needs to be patched in Dolfin? There are two important libraries: `libdmumps.dylib` and `libmumps_common.dylib`. The only difference with a standard MUMPS build is that they're shared instead of static.

What I don't understand is that PETSc is happy with the brewed MUMPS. The MUMPS libs appear correctly in the PETSc `variables` file. I'm not sure why Dolfin doesn't rely on it. For example, if I download http://www.mcs.anl.gov/petsc/petsc-current/src/ksp/ksp/examples/tutorials/ex52.c and build with
```
clang -o ex52 ex52.c -L/usr/local/opt/petsc/real/lib -lpetsc -lmpi
```
there's no problem.

**Comment by lukeolson** [comment]
Ok this is helpful.  Here's a collection of notes.  It looks like when PETSc links to MUMPS, then  the `dumps_c` symbols is undefined in `libpetsc.dylib`:
```
$ nm libpetsc.dylib | grep dmumps_c
10930:                 U _dmumps_c
```

But when it downloads and builds, it shows up:
```
$ nm libpetsc.dylib | grep dmumps_c
11637:000000000099a5ef T _dmumps_c
```

What must be happening is that dolfin is linking to MUMPS through `libpetsc.dylib`.  I think in the `ex52` example it's not actually calling `dmumps_c`.  I made a few lines to initialize the MUMPS struct to test calling `dmumps_c`:  https://gist.github.com/lukeolson/f4e34f0c33852179292d

This results in 

clang++ -o blank_mumps blank_mumps.cpp -L/usr/local/opt/petsc/real/lib -lpetsc -lmpi -I/usr/local/opt/mumps/include
Undefined symbols for architecture x86_64:
  "_dmumps_c", referenced from:
      _main in blank_mumps-cccf50.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

But when I build PETSC with `--download-mumps=1` this results in build that passes (except for some unrelated MPI init issues...I'll fix the gist).

So what to do?  Unless we can pass the libmumps library to the dolfin linker, I think we need to press on the `petsc` formula to include an option to build mumps itself or see if the `mumps` formula can build as static (I have no idea if this would fix it though).  I don't see how to patch the `dolfin` formula yet to get around this issue.

**Comment by lukeolson** [comment]
Here's a better example to test with:
https://www.nersc.gov/users/software/programming-libraries/math-libraries/petsc/c-example-mumps/

**Comment by dpo** [comment]
I'm not understanding why dependencies in the dylibs aren't being followed. Isn't that the whole point of dylibs?
```
$ otool -L /usr/local/opt/petsc/real/lib/libpetsc.dylib | grep mumps
	/usr/local/opt/mumps/lib/libcmumps.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/mumps/lib/libdmumps.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/mumps/lib/libsmumps.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/mumps/lib/libzmumps.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/mumps/lib/libmumps_common.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/mumps/lib/libpord.dylib (compatibility version 0.0.0, current version 0.0.0)
```
I must be building the MUMPS dylibs wrong.

**Comment by dpo** [comment]
At least as a temporary workaround, if I build the static MUMPS libs and ask PETSc to link against those, your test program runs. I'll now see if Dolfin builds.

**Comment by dpo** [comment]
Success! The build completed! Now I need to update the `mumps`, `petsc` and `slepc` bottles.

**Comment by lukeolson** [comment]
Great!  One thought...would it change if petsc is built from source rather than poured? (I'm trying now)

**Comment by dpo** [comment]
It's taking longer than planned because `petsc` isn't brewed with threads by default and that causes `dolfin` to crash. But we're getting there.

**Comment by lukeolson** [comment]
Are you using any flags with the builds?

I end up with the following warning:
```
==> make install
Warning: optimizers/fenics/dolfin dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
```

And then with `demo_poisson.py`:

```
Fatal Python error: PyThreadState_Get: no current thread
[trout:84845] *** Process received signal ***
[trout:84845] Signal: Abort trap: 6 (6)
[trout:84845] Signal code:  (0)
[trout:84845] [ 0] 0   libsystem_platform.dylib            0x00007fff8cf92eaa _sigtramp + 26
[trout:84845] [ 1] 0   ???                                 0x00007fc0d41c9980 0x0 + 140466169092480
[trout:84845] [ 2] 0   libsystem_c.dylib                   0x00007fff94a276e7 abort + 129
[trout:84845] [ 3] 0   Python                              0x00000001140d1ce2 Py_FatalError + 49
[trout:84845] [ 4] 0   Python                              0x00000001140d11f0 PyThreadState_Get + 28
[trout:84845] [ 5] 0   Python                              0x00000001140ce03a Py_InitModule4_64 + 62
[trout:84845] [ 6] 0   _ffc_form_030172ac36a54f6832c74e6833003d3326a83aa3.so 0x000000011eaf2f50 init_ffc_form_030172ac36a54f6832c74e6833003d3326a83aa3 + 800
[trout:84845] [ 7] 0   Python                              0x000000010fc50973 _PyImport_LoadDynamicModule + 140
[trout:84845] [ 8] 0   Python                              0x000000010fc5040a imp_load_module + 243
[trout:84845] [ 9] 0   Python                              0x000000010fc3abcd PyEval_EvalFrameEx + 26858
[trout:84845] [10] 0   Python                              0x000000010fc3e72d fast_function + 264
[trout:84845] [11] 0   Python                              0x000000010fc3aaf3 PyEval_EvalFrameEx + 26640
[trout:84845] [12] 0   Python                              0x000000010fc340f1 PyEval_EvalCodeEx + 1583
[trout:84845] [13] 0   Python                              0x000000010fc33abc PyEval_EvalCode + 54
[trout:84845] [14] 0   Python                              0x000000010fc4cef7 PyImport_ExecCodeModuleEx + 241
[trout:84845] [15] 0   Python                              0x000000010fc4fc0f load_source_module + 1089
[trout:84845] [16] 0   Python                              0x000000010fc4f671 import_submodule + 267
[trout:84845] [17] 0   Python                              0x000000010fc4f237 load_next + 284
[trout:84845] [18] 0   Python                              0x000000010fc4e41b PyImport_ImportModuleLevel + 1139
[trout:84845] [19] 0   Python                              0x000000010fc2f6f2 builtin___import__ + 135
[trout:84845] [20] 0   Python                              0x000000010fbbaeb0 PyObject_Call + 99
[trout:84845] [21] 0   Python                              0x000000010fc3e06f PyEval_CallObjectWithKeywords + 165
[trout:84845] [22] 0   Python                              0x000000010fc39372 PyEval_EvalFrameEx + 20623
[trout:84845] [23] 0   Python                              0x000000010fc340f1 PyEval_EvalCodeEx + 1583
[trout:84845] [24] 0   Python                              0x000000010fc33abc PyEval_EvalCode + 54
[trout:84845] [25] 0   Python                              0x000000010fc4cef7 PyImport_ExecCodeModuleEx + 241
[trout:84845] [26] 0   Python                              0x000000010fc4fc0f load_source_module + 1089
[trout:84845] [27] 0   Python                              0x000000010fc4fe94 load_package + 303
[trout:84845] [28] 0   Python                              0x000000010fc4f671 import_submodule + 267
[trout:84845] [29] 0   Python                              0x000000010fc4f237 load_next + 284
[trout:84845] *** End of error message ***
[1]    84845 abort      python demo_poisson.py
```


So there are some thread issues.

**Comment by dpo** [comment]
https://github.com/optimizers/homebrew-fenics/tree/dolfin160#troubleshooting

**Comment by dpo** [comment]
That's what I've been struggling with for the past day. I suspect we'll get of a lot of issues related to it.

**Comment by dpo** [comment]
Keep in mind it could be your IPython (if that's what you use) that uses a different interpreter.

**Comment by dpo** [comment]
@lukeolson Any success?

**Comment by lukeolson** [comment]
I wiped nearly everything (following the troubleshooting) and still end up with the same thing.  I note it still complains about libstdc++.

I’ll try again to make sure I didn’t have something off

**Comment by dpo** [comment]
Any luck? I'm trying to get Dolfin to build on Travis but it times out.
