### ISSUE TITLE
Fortran error! mpif.h could not be located

### ISSUE THREAD

**Issue by RICQP** [optimizers/homebrew-fenics#7]
Hi,

I try to install **fenics/Dolfin** via **Homebrew**.  Following the instructions, when run 

    brew install optimizers/fenics/petsc-fenics --env=std

I get the error message

    Fortran error! mpif.h could not be located at: []

I thank you in advance for your help

Ricardo

The complete log file is in:

https://gist.github.com/8d1b8e6042cd51c3e36e

**Comment by dpo** [comment]
We've been having issues with the `:mpi` dependency at Homebrew/Science. Does it build if you manually `brew install open-mpi` (or `mpich`) first?

**Comment by RICQP** [comment]
Hi, Thank you for your answer.

I have install manually open-mpi (from http://www.open-mpi.org), and all run fine until the line

    $ brew install dolfin --env=std
Here, when you try to install **hdf5** I get an error : 
    ld: symbol(s) not found for architecture x86_64

I thank you in advance for your help

Ricardo

The complete log file is in:

https://gist.github.com/282c3c00711c68eaf2d4

**Comment by dpo** [comment]
I'm not sure yet what the actual problem is but I notice that somehow ]you ended up with `-std=c99` in your build flags](https://gist.github.com/anonymous/282c3c00711c68eaf2d4#file-01-configure-L456). `brew doctor` reports lots of potential issues, including the fact that you seem to have another installation of MPI around. I wonder if there's some mixup in the `mpicc`, `mpif77`, etc. Could you try removing the old install of MPI first?

**Comment by RICQP** [comment]
I tried to install openmpi manually, but at some point dolfin sends the mistake that I had communicated to you. I start a new installation (from null)  and find a similar  error. The log is below.

https://gist.github.com/a3ec956e6960c03c347b

Thank you very much for the attention,
Richard

**Comment by dpo** [comment]
What I'm recommending is to install everything via Homebrew, i.e., removing all the non-Homebrew dependencies of `dolfin` if possible, and letting Homebrew manage them.

**Comment by RICQP** [comment]
Hi, I follow your recommendation and have to install everything via Homebrew, but i found a problem with the installation of **slepc**. The log is below.

https://gist.github.com/a01de4dfcc11cf68cc88

Another question: Is there no conflict between the version of **petsc-fenics** (3.4) and the version that dolphin install (**petsc-lite** 3.6) ?

Thank you very much for the attention,
Richard

**Comment by RICQP** [comment]
I have installed  the  dependencies of  **Dolfin** (without  **slepc**), but for dolphin i found that  UF_long is deprecated 

     /tmp/dolfin20151124-2448-1sk4rsc/dolfin-1.4.0/dolfin/la/CholmodCholeskySolver.cpp:202:56: error:   unknown type name 'UF_long'
     void CholmodCholeskySolver::Cholmod::init(UF_long* Ap, UF_long* Ai, double* Ax,
                                                       ^
     /tmp/dolfin20151124-2448-1sk4rsc/dolfin-1.4.0/dolfin/la/CholmodCholeskySolver.cpp:336:3: error:      unknown type name 'UF_long'; did you mean 'u_long'?
      UF_long status = c.status;
       ^~~~~~~
      u_long
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.1     1.sdk/usr/include/sys/types.h:88:24: note: 'u_long' declared here
    typedef unsigned long           u_long;
                                ^
    7 errors generated.
    make[2]: *** [dolfin/CMakeFiles/dolfin.dir/la/CholmodCholeskySolver.cpp.o] Error 1
    make[1]: *** [dolfin/CMakeFiles/dolfin.dir/all] Error 2
    make: *** [all] Error 2   


The log is below.

https://gist.github.com/244b07e594c098f0391e

Thank you very much for the attention,

Ricardo

**Comment by RICQP** [comment]
Hi, I installed mpich instead of open-mpi and the installation fail for **dolfin**  for the dependency  **superlu_dist**

    ==> Installing optimizers/fenics/dolfin dependency: superlu_dist
    ==> Using Homebrew-provided fortran compiler.
    This may be changed by setting the FC environment variable.
    ==> Downloading http://crd-legacy.lbl.gov/~xiaoye/SuperLU/superlu_dist_4.1.tar.gz
    ######################################################################## 100.0%
    ==> Downloading https://bitbucket.org/petsc/pkg-superlu_dist/commits/2faf8669a2ba20250ffe2d8a1b63d
    ######################################################################## 100.0%

    Error: SHA256 mismatch
    Expected: 09dcd7de83ef9d2590465742df76753cb7c61bfe8e7819c02613d9bcf20ed255
    Actual: 67e2966e1a9b4e3471374d1e720946c2ef34403d00e796767b51718e4d50604f
    Archive: /Library/Caches/Homebrew/superlu_dist--patch-    09dcd7de83ef9d2590465742df76753cb7c61bfe8e7819c02613d9bcf20ed255
    To retry an incomplete download, remove the file above.

But, wenn i remove the file and re-start the installation for **dolfin**, i become

       $ brew reinstall dolfin --env=std
       ==> Installing dolfin from optimizers/homebrew-fenics
       Error: You must `brew link suite-sparse metis parmetis` before optimizers/fenics/dolfin can be installed
        $ brew doctor
       Please note that these warnings are just used to help the Homebrew maintainers
       with debugging if you file an issue. If everything you use Homebrew for is
       working fine: please don't worry and just ignore them. Thanks!

     Warning: You have unlinked kegs in your Cellar
     Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
     those kegs to fail to run properly once built. Run `brew link` on these:
        metis
        open-mpi
        parmetis
        suite-sparse

Thank for your attention

Ricardo

**Comment by dpo** [comment]
Sorry for the long silence. Lots has happened in Homebrew since. Are you still having the same issues?

**Comment by dpo** [comment]
Please `brew update` and open a new issue if you're still have difficulties.
