### ISSUE TITLE
Dolfin make error: unknown type name 'UF_long'

### ISSUE THREAD

**Issue by felbelles** [optimizers/homebrew-fenics#8]
Hello, 

I'm trying to install the homebrew dolfin on mac osx Yosemite (10.10.5) using the instructions at https://github.com/optimizers/homebrew-fenics

I get to the make stage, where I encounter the error below (see attached 02.make.txt file for full make output). Details about the environment are in the attached 03.env.txt file.

Also, in the configure stage, SLEPc could not be found, despite it being installed in SLEPC_DIR (see attached 01.cmake.txt configuration output).

Any assistance would be much appreciated!

Felicity

Error message:
/tmp/dolfin20160212-53945-of9e0o/dolfin-1.4.0/dolfin/la/CholmodCholeskySolver.cpp:96:17: error: use of undeclared identifier 'UF_long'
  cholmod.init((UF_long*) boost::tuples::get<0>(data),
                ^
/tmp/dolfin20160212-53945-of9e0o/dolfin-1.4.0/dolfin/la/CholmodCholeskySolver.cpp:96:25: error: expected expression
  cholmod.init((UF_long*) boost::tuples::get<0>(data),
                        ^
/tmp/dolfin20160212-53945-of9e0o/dolfin-1.4.0/dolfin/la/CholmodCholeskySolver.cpp:97:17: error: use of undeclared identifier 'UF_long'
               (UF_long*) boost::tuples::get<1>(data),
                ^
/tmp/dolfin20160212-53945-of9e0o/dolfin-1.4.0/dolfin/la/CholmodCholeskySolver.cpp:97:25: error: expected expression
               (UF_long*) boost::tuples::get<1>(data),
                        ^
/tmp/dolfin20160212-53945-of9e0o/dolfin-1.4.0/dolfin/la/CholmodCholeskySolver.cpp:202:43: error: unknown type name 'UF_long'
void CholmodCholeskySolver::Cholmod::init(UF_long* Ap, UF_long* Ai, double* Ax,
                                          ^
/tmp/dolfin20160212-53945-of9e0o/dolfin-1.4.0/dolfin/la/CholmodCholeskySolver.cpp:202:56: error: unknown type name 'UF_long'
void CholmodCholeskySolver::Cholmod::init(UF_long* Ap, UF_long* Ai, double* Ax,
                                                       ^
/tmp/dolfin20160212-53945-of9e0o/dolfin-1.4.0/dolfin/la/CholmodCholeskySolver.cpp:336:3: error: unknown type name 'UF_long'; did you mean 'u_long'?
  UF_long status = c.status;
  ^~~~~~~
  u_long
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/sys/types.h:88:24: note: 'u_long' declared here
typedef unsigned long           u_long;

7 errors generated.
make[2]: *** [dolfin/CMakeFiles/dolfin.dir/la/CholmodCholeskySolver.cpp.o] Error 1
make[1]: *** [dolfin/CMakeFiles/dolfin.dir/all] Error 2
make: *** [all] Error 2

[01.cmake.txt](https://github.com/optimizers/homebrew-fenics/files/127366/01.cmake.txt)
[02.make.txt](https://github.com/optimizers/homebrew-fenics/files/127365/02.make.txt)
[03.env.txt](https://github.com/optimizers/homebrew-fenics/files/127369/03.env.txt)

**Comment by dpo** [comment]
I'm working on the [`dolfin160`](https://github.com/optimizers/homebrew-fenics/tree/dolfin160) branch and getting there. Everything else is outdated. Give it a go if you'd like.

**Comment by felbelles** [comment]
Thanks for that @dpo. Have I done something very stupid when trying to get dolfin160...? See below.

$ brew install https://github.com/optimizers/homebrew-fenics/blob/dolfin160/dolfin.rb
######################################################################## 100.0%
Error: /Library/Caches/Homebrew/Formula/dolfin.rb:5: syntax error, unexpected '<'
<!DOCTYPE html>
 ^
/Library/Caches/Homebrew/Formula/dolfin.rb:6: syntax error, unexpected '<'
<html lang="en" class="">
 ^
/Library/Caches/Homebrew/Formula/dolfin.rb:6: syntax error, unexpected keyword_class, expecting end-of-input
<html lang="en" class="">
                     ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:23:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:23:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:85:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:140:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:76:in `klass'
/usr/local/Library/Homebrew/formulary.rb:72:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:18:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:45:in `install'
/usr/local/Library/brew.rb:85:in `<main>'

**Comment by felbelles** [comment]
Thanks @dpo. Had a go at install with following command:
brew install https://raw.githubusercontent.com/optimizers/homebrew-fenics/dolfin160/dolfin.rb

However, I get an issue where homebrew will always try to install fiat version 1.4.0, rather than the updated versions in your dolfin160 link. Is this ok? Otherwise, is there a way to specify a particular version of the dependencies upon which a package relies during install?

**Comment by felbelles** [comment]
Hey @dpo. Have been able to build dolfin160. In the make, I came across the same mumps error documented in https://github.com/optimizers/homebrew-fenics/issues/5. I ended up building dolfin from source and it seems to be working fine. Thanks

**Comment by dpo** [comment]
Please `brew update`.
