### ISSUE TITLE
problems installing petsc-fenics

### ISSUE THREAD

**Issue by francispoulin** [optimizers/homebrew-fenics#9]
Sorry to bug you with what maybe a simple problem but I am very lost.

I am trying to install fenics on my mac and having a difficult time.  I have tried
1) using curl 
2) using binary
3) using homebrew
and they have all failed.  I like the idea of using homebrew and found these instructions,

https://github.com/optimizers/homebrew-fenics

Unfortunately, I get it to work.  Any advice would be greatly appreciated.

$ brew install optimizers/fenics/petsc-fenics --env=std
==> Installing petsc-fenics from optimizers/fenics
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.4.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/petsc-fenics-3.4.4.tar.gz
==> ./configure --with-debugging=0 --with-shared-libraries=1 --prefix=/usr/local/Cellar/petsc-fenics/3.4.4/arch-darwin-c-opt --with-x=0 --download-hypre --download-metis -
Last 15 lines from /Users/fpoulin/Library/Logs/Homebrew/petsc-fenics/01.configure:
  make[1]: *** [CMakeFiles/cmTC_0b532.dir/testCXXCompiler.cxx.o] Error 1

  make: *** [cmTC_0b532/fast] Error 2

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

*******************************************************************************

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/optimizers/homebrew-fenics/issues

**Comment by dpo** [comment]
I'm working on the [`dolfin160`](https://github.com/optimizers/homebrew-fenics/tree/dolfin160) branch and getting there. Everything else is outdated. Give it a go if you'd like.

**Comment by francispoulin** [comment]
Thanks.  I am trying it out and getting to the point where everything is installed but dolfin.  Nearly there.

Here is the error.  I tried removing the swig file and trying again but that didn't quite do it.  Any advice?

==> Pouring swig-3.0.8.yosemite.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/ccache-swig
Target /usr/local/bin/ccache-swig
already exists. You may want to remove it:
  rm '/usr/local/bin/ccache-swig'

To force the link and overwrite all conflicting files:
  brew link --overwrite swig

To list all files that would be deleted:
  brew link --overwrite --dry-run swig

Possible conflicting files are:
/usr/local/bin/ccache-swig
/usr/local/bin/swig
==> Summary
🍺  /usr/local/Cellar/swig/3.0.8: 733 files, 5.2M
==> Installing optimizers/fenics/dolfin dependency: petsc-fenics
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.4.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/petsc-fenics-3.4.4.tar.gz
==> ./configure --with-debugging=0 --with-shared-libraries=1 --prefix=/usr/local/Cellar/petsc-fenics/3.4.4/arch-darwin-c-opt --down
Last 15 lines from /Users/fpoulin/Library/Logs/Homebrew/petsc-fenics/01.configure:
  fault: 11

  make: *** [cmTC_249f8/fast] Error 2

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


*******************************************************************************


READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/optimizers/homebrew-fenics/issues

Francis-Poulins-MacBook-Pro:~ fpoulin$ brew install dolfin
==> Installing dolfin from optimizers/fenics
==> Installing dependencies for optimizers/fenics/dolfin: petsc-fenics, scotch, pastix, hdf5, boost, vtk, fiat, ufl, ffc, in
==> Installing optimizers/fenics/dolfin dependency: petsc-fenics
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.4.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/petsc-fenics-3.4.4.tar.gz
==> ./configure --with-debugging=0 --with-shared-libraries=1 --prefix=/usr/local/Cellar/petsc-fenics/3.4.4/arch-darwin-c-opt --down
Last 15 lines from /Users/fpoulin/Library/Logs/Homebrew/petsc-fenics/01.configure:
  fault: 11

  make: *** [cmTC_e609a/fast] Error 2

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


*******************************************************************************


READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/optimizers/homebrew-fenics/issues

**Comment by dpo** [comment]
There seem to be conflicting files:
```
Possible conflicting files are:
/usr/local/bin/ccache-swig
/usr/local/bin/swig
```
Did you install `swig` in some other way? What does `brew doctor` say?

**Comment by francispoulin** [comment]
From what I can tell they were both installed by homebrew.  

Francis-Poulins-MacBook-Pro:~ fpoulin$ ls -lrt /usr/local/bin/swig 
lrwxr-xr-x  1 fpoulin  admin  29 13 Feb 13:26 /usr/local/bin/swig -> ../Cellar/swig/3.0.8/bin/swig
Francis-Poulins-MacBook-Pro:~ fpoulin$ ls -lrt /usr/local/bin/ccache-swig
lrwxr-xr-x  1 fpoulin  admin  36 13 Feb 13:26 /usr/local/bin/ccache-swig -> ../Cellar/swig/3.0.8/bin/ccache-swig

My brew doctor tells me a lot of things (that I should probably sort out) but I can't see anything involving swig.   Should I uninstall both and start again fresh?

**Comment by dpo** [comment]
Could you try `brew uninstall swig`, and post the output of `brew doctor`?

**Comment by francispoulin** [comment]
I removed swig and brew doctor does not give me any errors.  There are warnings about a lot of extra files but I think those are always there.

I can copy all of this if you want but I don't think there is anything about swig.  Maybe I'll try installing dolfin again, just to see if things have changed.

**Comment by francispoulin** [comment]
I removed swig and tried to install dolfin again.  I noticed that it installed both versions of swig at the sametime.

I am a little surprised that it's installing petsc lite since I thought that petsc was already installed.  But I'm going blind here so this is just a feeling, not anything well informed.

[I cleaned up my unbrewed files, in case it was because of that.]

Francis-Poulins-MacBook-Pro:~ fpoulin$ brew uninstall swig
Uninstalling /usr/local/Cellar/swig/3.0.8... (733 files, 5.2M)
Francis-Poulins-MacBook-Pro:~ fpoulin$ brew doctor
Your system is ready to brew.
Francis-Poulins-MacBook-Pro:~ fpoulin$ brew install dolfin
==> Installing dolfin from optimizers/fenics
==> Installing dependencies for optimizers/fenics/dolfin: swig, petsc-fenics, scotch, pastix, hdf5, boost, vtk, fiat, ufl, ffc, instant
==> Installing optimizers/fenics/dolfin dependency: swig
==> Downloading https://homebrew.bintray.com/bottles/swig-3.0.8.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/swig-3.0.8.yosemite.bottle.tar.gz
==> Pouring swig-3.0.8.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/swig/3.0.8: 733 files, 5.2M
==> Installing optimizers/fenics/dolfin dependency: petsc-fenics
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.4.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/petsc-fenics-3.4.4.tar.gz
==> ./configure --with-debugging=0 --with-shared-libraries=1 --prefix=/usr/local/Cellar/petsc-fenics/3.4.4/arch-darwin-c-opt --download-hypre --d
Last 15 lines from /Users/fpoulin/Library/Logs/Homebrew/petsc-fenics/01.configure:
  fault: 11

  make: *** [cmTC_f040c/fast] Error 2

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


*******************************************************************************

**Comment by dpo** [comment]
You're not on the `dolfin160` branch. Go to `/usr/local/Library/Taps/optimizers/homebrew-fenics` and type `git checkout dolfin160`. Then
```
brew uninstall ffc fiat instant ufl
brew install dolfin
```
It currently expected that `dolfin` will fail at 93% because of a `mumps` dependency. I'm looking into that. The rest should install and `dolfin` should detect every optional dependency.

**Comment by francispoulin** [comment]
Thanks for the help.  Sorry that I didn't realize I need to do this on git.

I tried what you suggested, see below, but it says there is no branch, but when I go to 

https://github.com/optimizers/homebrew-fenics

I see that there is such a branch, as you know.  Sorry that I'm not very able in git.  Any advice?

Francis-Poulins-MacBook-Pro:homebrew-fenics fpoulin$ pwd
/usr/local/Library/Taps/optimizers/homebrew-fenics
Francis-Poulins-MacBook-Pro:homebrew-fenics fpoulin$ git branch
* master
Francis-Poulins-MacBook-Pro:homebrew-fenics fpoulin$ git checkout dolfin160
error: pathspec 'dolfin160' did not match any file(s) known to git.
Francis-Poulins-MacBook-Pro:homebrew-fenics fpoulin$ git pull
Already up-to-date.
Francis-Poulins-MacBook-Pro:homebrew-fenics fpoulin$ git checkout dolfin160
error: pathspec 'dolfin160' did not match any file(s) known to git.

**Comment by francispoulin** [comment]
When I show the possible branches I don't see dolfin160.

Francis-Poulins-MacBook-Pro:homebrew-fenics fpoulin$ git pull
Already up-to-date.
Francis-Poulins-MacBook-Pro:homebrew-fenics fpoulin$ git show-branch --all
* [master] Update README.md
 ! [origin/HEAD] Update README.md
  ! [origin/master] Update README.md
---
*++ [master] Update README.md

**Comment by dpo** [comment]
`git fetch`?

**Comment by francispoulin** [comment]
I tried git pull, fetch and checked the url.  They look to be the same.  Also, when I go to github I see that there is a dolfin160.  I am tempted to try git cloning myself but that seems like a bad idea.

Francis-Poulins-MacBook-Pro:homebrew-fenics fpoulin$ git pull
Already up-to-date.
Francis-Poulins-MacBook-Pro:homebrew-fenics fpoulin$ git fetch
Francis-Poulins-MacBook-Pro:homebrew-fenics fpoulin$ git remote -v
origin	https://github.com/optimizers/homebrew-fenics (fetch)
origin	https://github.com/optimizers/homebrew-fenics (push)
Francis-Poulins-MacBook-Pro:homebrew-fenics fpoulin$ git checkout dolfin160
error: pathspec 'dolfin160' did not match any file(s) known to git.

**Comment by francispoulin** [comment]
Somehow, now I'm on dolfin160.  Not sure what I messed up on but this is good news I guess.

Unfortunately, I still get the same error.  Should I remove more stuff and try again?

Francis-Poulins-MacBook-Pro:homebrew-fenics fpoulin$ git branch
* dolfin160
  master
Francis-Poulins-MacBook-Pro:homebrew-fenics fpoulin$ brew install dolfin
==> Installing dolfin from optimizers/fenics
==> Installing dependencies for optimizers/fenics/dolfin: petsc-fenics, scotch, pastix, hdf5, boost, vtk, fiat, ufl, ffc, instant
==> Installing optimizers/fenics/dolfin dependency: petsc-fenics
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.4.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/petsc-fenics-3.4.4.tar.gz
==> ./configure --with-debugging=0 --with-shared-libraries=1 --prefix=/usr/local/Cellar/petsc-fenics/3.4.4/arch-darwin-c-opt --download-hypre --download-metis --download-parmetis --downloa
Last 15 lines from /Users/fpoulin/Library/Logs/Homebrew/petsc-fenics/01.configure:
  fault: 11

  make: *** [cmTC_47c16/fast] Error 2

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


*******************************************************************************

**Comment by francispoulin** [comment]
I decided to uninstall python and start from scratch. Not much better I'm afraid.  But now, when I uninstall swig, brew doctor says that swig is missing:

## Step 1
Francis-Poulins-MacBook-Pro:homebrew-fenics fpoulin$ brew uninstall swig
Uninstalling /usr/local/Cellar/swig/3.0.8... (733 files, 5.2M)
Francis-Poulins-MacBook-Pro:homebrew-fenics fpoulin$ ls -lrt /usr/local/bin/*swig*
ls: /usr/local/bin/*swig*: No such file or directory

## Step 2
Francis-Poulins-MacBook-Pro:homebrew-fenics fpoulin$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:

    brew install swig

Run `brew missing` for more details.

## Step 3
Francis-Poulins-MacBook-Pro:homebrew-fenics fpoulin$ brew missing
optimizers/fenics/instant: swig

I then installed swig and tried to install dolfin, but with the same error message as before.

Sorry that I won't able to find anything more constructive.

**Comment by francispoulin** [comment]
Sorry to bug you again but do take it that the dolfin160 is not yet working?  I would much rather use the homebrew version rather than the binary and am happy to do more testing if that would help.

**Comment by dpo** [comment]
It works for me at least, but I haven't yet received any other feedback. Please try:
```
cd $(brew --repo)/Library/Taps/optimizers/homebrew-fenics
git checkout dolfin160
git pull
brew uninstall --force $(brew deps dolfin)
```
You'll want to make sure that system Python appears first in your PATH. Then follow the instructions in the [`README`](https://github.com/optimizers/homebrew-fenics/blob/dolfin160/README.md).

Let me know how it goes.

**Comment by francispoulin** [comment]
I followed the instructions you suggested. It seems to remove a lot of the stuff that I had installed and starts from scratch.  Very good idea.

Everything seemed to go well up until it gets to swig.  This error seems different from before.  

I see that there is both a swig and ccache-swig installed, in case that helps.

Thanks for the help and sorry that this is a pain to fix.

==> Pouring swig-3.0.8.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/swig/3.0.8: 733 files, 5.2M
==> Installing optimizers/fenics/dolfin dependency: petsc-fenics
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.4.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/petsc-fenics-3.4.4.tar.gz
==> ./configure --with-debugging=0 --with-shared-libraries=1 --prefix=/usr/local/Cellar/petsc-fenics/3.4.4/arch-darwin-c-opt --download-hypre --download-metis --download
Last 15 lines from /Users/fpoulin/Library/Logs/Homebrew/petsc-fenics/01.configure:
  fault: 11

  make: *** [cmTC_d2b38/fast] Error 2

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


*******************************************************************************


READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/optimizers/homebrew-fenics/issues

**Comment by francispoulin** [comment]
I am copying the tail of the configure file.  One problem that I see is that it is using /usr//bin/python, instead of the hombrew version, /usr/local/bin/python. 



                        Configuring METIS; this may take several minutes
                    ===============================================================================
                  
*******************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
Error running configure on METIS: Could not execute "cd /private/tmp/petsc-fenics20160222-65942-1am2hq8/petsc-3.4.4/externalpackages/metis-5.0.2-p3/arch-darwin-c-opt && /usr/local/opt/cmake/bin/cmake .. -DCMAKE_INSTALL_PREFIX=/private/tmp/petsc-fenics20160222-65942-1am2hq8/petsc-3.4.4/arch-darwin-c-opt -DCMAKE_VERBOSE_MAKEFILE=1 -DGKLIB_PATH=../GKlib -DCMAKE_C_COMPILER="mpicc" -DCMAKE_AR=/usr/bin/ar -DCMAKE_RANLIB=/usr/bin/ranlib -DCMAKE_C_FLAGS:STRING=" -fPIC -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -O " -DSHARED=1 -DMETIS_USE_DOUBLEPRECISION=1":
-- The C compiler identification is AppleClang 7.0.2.7000181
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/local/bin/mpicc
-- Check for working C compiler: /usr/local/bin/mpicc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/bin/g++
-- Check for working CXX compiler: /usr/local/bin/g++ -- broken
-- Configuring incomplete, errors occurred!
See also "/tmp/petsc-fenics20160222-65942-1am2hq8/petsc-3.4.4/externalpackages/metis-5.0.2-p3/arch-darwin-c-opt/CMakeFiles/CMakeOutput.log".
See also "/tmp/petsc-fenics20160222-65942-1am2hq8/petsc-3.4.4/externalpackages/metis-5.0.2-p3/arch-darwin-c-opt/CMakeFiles/CMakeError.log".
CMake Error at /usr/local/Cellar/cmake/3.4.3/share/cmake/Modules/CMakeTestCXXCompiler.cmake:54 (message):
  The C++ compiler "/usr/local/bin/g++" is not able to compile a simple test
  program.

  It fails with the following output:

   Change Dir: /tmp/petsc-fenics20160222-65942-1am2hq8/petsc-3.4.4/externalpackages/metis-5.0.2-p3/arch-darwin-c-opt/CMakeFiles/CMakeTmp

  

  Run Build Command:"/usr/local/Library/ENV/4.3/gmake" "cmTC_d2b38/fast"

  /Applications/Xcode.app/Contents/Developer/usr/bin/make -f
  CMakeFiles/cmTC_d2b38.dir/build.make CMakeFiles/cmTC_d2b38.dir/build

  Building CXX object CMakeFiles/cmTC_d2b38.dir/testCXXCompiler.cxx.o

  /usr/local/bin/g++ -o CMakeFiles/cmTC_d2b38.dir/testCXXCompiler.cxx.o -c
  /tmp/petsc-fenics20160222-65942-1am2hq8/petsc-3.4.4/externalpackages/metis-5.0.2-p3/arch-darwin-c-opt/CMakeFiles/CMakeTmp/testCXXCompiler.cxx


  make[1]: *** [CMakeFiles/cmTC_d2b38.dir/testCXXCompiler.cxx.o] Segmentation
  fault: 11

  make: *** [cmTC_d2b38/fast] Error 2


  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 937e6a80af7418b157771d0eddb38b2fc35f519e
Last commit: 9 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit ivybridge
OS X: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
GCC-4.2: build 0
Clang: 7.0 build 700
X11: 2.7.8 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.6.0_65-b14-468

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/opt/X11/include:/opt/X11/include/freetype2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /opt/X11/lib:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /usr/local/opt/open-mpi/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10:/opt/X11/lib/pkgconfig:/opt/X11/share/pkgconfig
ACLOCAL_PATH: /usr/local/share/aclocal:/opt/X11/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/cmake/bin:/usr/local/opt/open-mpi/bin:/usr/local/opt/gcc/bin:/opt/X11/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
am-laptop24:~ fpoulin$

**Comment by dpo** [comment]
I'm not sure why but it's still trying to install the old `petsc-fenics` that no longer exists. Here's what we'll do:
```
brew untap optimizers/fenics
brew tap --repair
brew tap optimizers/fenics
cd $(brew --repo)/Library/Taps/optimizers/homebrew-fenics
git fetch
git checkout dolfin160
```
At this point, please confirm that you are in branch `dolfin160`:
```
$ git branch
  dolfin1.5
  dolfin1.5-debug
* dolfin160
  master
  travis
```
The `*` should be in front of `dolfin160`. Until you can make sure you're on the right branch, there's no point in continuing. Once that's done, continue the installation:
```
brew uninstall $(brew deps --recursive dolfin)
```
and follow the `README`.

**Comment by francispoulin** [comment]
That was a good idea.  If its trying to install petsc-fenics, then clearly I am on the wrong branch.

I followed the steps you suggested and see that it can't find dolfin160.  I wonder whether before I might have created my own dolfin160 branch.  If that was the case then it's gone, but I can't see to find dolfin160, even though I know it does exist.  I thought I figured this out before but clearly I didn't.  

am-laptop24:homebrew-fenics fpoulin$ git checkout dolfin160
error: pathspec 'dolfin160' did not match any file(s) known to git.
am-laptop24:homebrew-fenics fpoulin$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master

**Comment by dpo** [comment]
`git fetch origin` should fetch all the remote branches. If it doesn't, something else is wrong and I'm not sure what. Perhaps `git checkout -b dolfin160 origin/dolfin160` will work?!

**Comment by francispoulin** [comment]
I deleted homebrew-fenics and then git cloned it and I'm now on the right branch.  I am going to proceed but if you think this might mess things up please let me know.

**Comment by francispoulin** [comment]
That was a bad idea.  I removed it, untaped homebrew-fenics and retapped it.  

Unfortunately, the syntax you suggested didn't work for me, see below.

Thanks again.

$ git checkout dolfin160
error: pathspec 'dolfin160' did not match any file(s) known to git.
am-laptop24:homebrew-fenics fpoulin$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
am-laptop24:homebrew-fenics fpoulin$ git checkout -b dolfin160 origin/dolfin160
fatal: Cannot update paths and switch to branch 'dolfin160' at the same time.
Did you intend to checkout 'origin/dolfin160' which can not be resolved as commit?

**Comment by francispoulin** [comment]
I tried a few things and this seemed to do the trick (for reasons that I don't understand really)

git fetch origin dolfin160:dolfin160

I just restarted the install and the good news is that it is no longer looking for petsc-fenics!

am-laptop24:homebrew-fenics fpoulin$ brew install dolfin
==> Installing dolfin from optimizers/fenics
==> Installing dependencies for optimizers/fenics/dolfin: qt, boost, libpng, freetype, fontconfig, jpeg, libtiff, homebrew/science/vtk, scotch, homebrew/science/pastix, homebr
==> Installing optimizers/fenics/dolfin dependency: qt
...

**Comment by dpo** [comment]
Excellent. Let me know how the installation goes.

**Comment by francispoulin** [comment]
The installation seemed to work.  brew doctor doesn't complain.  

But when I try to run a demo I get the following error.

Fatal Python error: PyThreadState_Get: no current thread

I realize this is a known problem and I found instructions in the README that suggest to start with this.  

brew rm $(brew deps --installed <problematic_formula>)

My question is now what should I insert for <problematic_formula>?

**Comment by francispoulin** [comment]
Maybe I spoke too soon about the installation working.

After I open the fenics environment, if I use /usr/local/bin/python then I get the error mentioned above.  That's not great but it's a start.

It seems that in the fenics environment, the default python is /Users/fpoulin/.virtualenvs/fenics/bin/python
and that can't import dolfin.  So it doesn't seem that the python that was built for fenics has access to the correct path.  Not sure what to do this this I'm afraid.

**Comment by dpo** [comment]
That's what I meant about making sure system Python appears first in your PATH. Also make sure to create the virtual environment for system Python (`mkvirtualenv --python=/usr/bin/python`). All Homebrew packages that have a Python dependency will build against system Python. If everything else built, then this is the last frontier. Also make sure to `brew install dolfin --without-trilinos` because Trilinos needs to be rebottled against system Python (see https://github.com/Homebrew/homebrew-science/pull/3314). I'm sorry if I forgot to mention that. This is a temporary annoyance only.

**Comment by francispoulin** [comment]
Sorry that I missed that.  I thought that homebrew python was supposed to be the first in the path so I had /usr/local/bin first but I have since changed it to /usr/bin, since you suggested that system Python should be first.  

Something that I find a real pain is that system Python installs pip in /usr/local/bin, as does homebrew.  It seems to me that I can have only one or the other but not both.  If you say that I need to use system Python than I will do that but it'd be nice to have a pip for each of them.  

To make sure that I get this, in the README, the pip that installs everything is for system Python?

I am puzzled though.  If that's the case then is the homebrew version of python used for anything?

**Comment by dpo** [comment]
You'll only need the `pip` in `/usr/local/bin` to install `virtualenv` and `virtualenvwrapper`. Once you've created a virtual environment (with system Python), you'll be using the pip that's in there.

**Comment by francispoulin** [comment]
I am having some problems but maybe I can ask a direction question. 

- You said that I need to have system Python in front of my homebrew python.
- This requires having /usr/bin in front of /usr/local/bin.  
- brew doctor doesn't like this.  

If I try anyhow I get the following, at least new error, see below. On the bright side it suggests a couple of way to fix it.  Do you suggest one in particular?

$ brew install dolfin --without-trilinos
==> Installing dolfin from optimizers/fenics
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://bitbucket.org/fenics-project/dolfin/downloads/dolfin-1.6.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/dolfin-1.6.0.tar.gz
==> cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/dolfin/1.6.0 -DBUILD_SHARED_LIBS:BOOL=ON -DDOLFIN_ENABLE_PYTHON:BOOL=ON -DDOLFIN_INSTALL_PYTHON_MODULE_DIR=/usr/local/Cell
Last 15 lines from /Users/fpoulin/Library/Logs/Homebrew/dolfin/01.cmake:

CMake Error at /Applications/CMake 2.8-10.app/Contents/share/cmake-2.8/Modules/Platform/Darwin.cmake:190 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.10' but CMAKE_OSX_SYSROOT:

   ""

  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.
Call Stack (most recent call first):
  /Applications/CMake 2.8-10.app/Contents/share/cmake-2.8/Modules/CMakeSystemSpecificInformation.cmake:36 (include)
  CMakeLists.txt:9 (project)


-- Configuring incomplete, errors occurred!

**Comment by dpo** [comment]
Sorry it's such a bumpy ride. What I did is `brew unlink python` before I started installing Dolfin to make sure it's not used.

Also I've not been very clear earlier. If you installed Homebrew Python, and it's linked, then it will appear first on the PATH, and that's the one Homebrew will use. However, it is Homebrew policy that all Python dependencies should build correctly with system Python if Homebrew Python isn't installed or linked. 

What's important here is that *everything* be built with *the same* Python interpreter. And Homebrew bottles are all built against system Python when possible.

So if you wanted to use Homebrew Python (e.g., because it's more recent), you would have to rebuild everything from source.

Hope that makes more sense.

**Comment by francispoulin** [comment]
Thanks.  Ok, so if I understand correctly then FEniCS will build its python using System Python, like the binary does.  

I tried to clean things up and build everything from scratch. Below is everything that I did, following your emails and then the README, but I still get the same error that I had yesterday.  

Can you see anything that I might be doing wrong?

-> make sure /usr/local/bin is before /usr/bin

-> Clean up.  
	brew uninstall python,  
	brew install python, 
	brew unlink python

	brew uninstall $(brew deps --recursive dolfin)

	rm -rf ~/.virtualenvs

	brew untap optimizers/fenics
	brew tap --repair
	brew tap optimizers/fenics
	cd $(brew —repo)/Library/Taps/optimizers/homebrew-fenics
	
	git fetch origin dolfin160:dolfin160
	git checkout dolfin160

-> Add Science and FEniCS taps

	brew tap homebrew/science
	brew tap optimizers/homebrew-fenics

-> Prepare (system) python 

	sudo eady_install pip

-> Make virtualenv

	mkdir -p ~/.virtualenvs
	export WORKON_HOME=$HOME/.virtualenvs >> ~/.bashrc
	source /usr/local/bin/virtualenvwrapper.sh >> ~/.bashrc

	mkvirtualenv —python=/usr/bin/python fenics
	workon fenics

——- Now in virtualenv ——-

-> Install python dependencies

	brew install slepc

	 pip install virtualenv
	 pip install virtualenvwrapper

-> in virtualenv

	brew install slepc
	
	pip install ply
	PETSC_DIR=/usr/local/opt/petsc/real SLEPC_DIR=/usr/local/opt/slepc/real pip install mpi4py petsc4py slepc4py
	
-> install dolfin

	brew install dolfin —without-trilinos

Get error:

$ brew install dolfin --without-trilinos
==> Installing dolfin from optimizers/fenics
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://bitbucket.org/fenics-project/dolfin/downloads/dolfin-1.6.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/dolfin-1.6.0.tar.gz
==> cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/dolfin/1.6.0 -DBUILD_SHARED_LIBS:BOOL=ON -DDOLFIN_ENABLE_PYTHON:BOOL=ON -DDOLFIN_INSTALL_PYTHON_MODULE_DIR=/usr/local/Cell
Last 15 lines from /Users/fpoulin/Library/Logs/Homebrew/dolfin/01.cmake:

CMake Error at /Applications/CMake 2.8-10.app/Contents/share/cmake-2.8/Modules/Platform/Darwin.cmake:190 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.10' but CMAKE_OSX_SYSROOT:

   ""

  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.
Call Stack (most recent call first):
  /Applications/CMake 2.8-10.app/Contents/share/cmake-2.8/Modules/CMakeSystemSpecificInformation.cmake:36 (include)
  CMakeLists.txt:9 (project)


-- Configuring incomplete, errors occurred!

**Comment by dpo** [comment]
I am going to merge #11 and we'll start fresh. There will be no need to change branch in the tap anymore. Thank you for your patience.

**Comment by dpo** [comment]
Please `brew update`.
